create table author (
        id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

create table post (
        id int8 generated by default as identity,
        body varchar(255),
        date timestamp,
        title varchar(255),
        id_author int8,
        primary key (id)
    ); 

alter table if exists post 
       add constraint FKihfu7cdj7hk21tah8sox7lnff 
       foreign key (id_author) 
       references author;